# Databricks Apps Configuration File
# This file defines how the application is deployed to Databricks Apps

# Application command - runs the Streamlit app
command:
  - "streamlit"
  - "run"
  - "app.py"
  - "--server.port"
  - "8501"
  - "--server.address"
  - "0.0.0.0"
  - "--server.headless"
  - "true"
  - "--browser.gatherUsageStats"
  - "false"

# Environment variables for the application
env:
  # Streamlit configuration
  - name: STREAMLIT_SERVER_ENABLE_CORS
    value: "false"
  - name: STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION
    value: "true"
  - name: STREAMLIT_BROWSER_GATHER_USAGE_STATS
    value: "false"
  # Python configuration
  - name: PYTHONUNBUFFERED
    value: "1"
